Vagrant.configure("2") do |config|

  config.vm.provision "shell", path: '../provisioning/bootstrap.sh'

  config.vm.define "kmaster" do |node|
    node.vm.box = "ubuntu/xenial64"    
    node.vm.hostname="kmaster"
    node.vm.network "private_network", ip: "192.168.2.100"
    node.vm.provision "shell", path: '../provisioning/bootstrap-kmaster.sh'
    node.vm.provision "shell", path: '../provisioning/bootstrap-calico.sh', privileged: false

    node.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end

  WorkersCount = 4

  (1..WorkersCount).each do |i|
    config.vm.define "kworker#{i}" do |node|
      node.vm.box = "ubuntu/xenial64"
      node.vm.hostname = "kworker#{i}"
      node.vm.network "private_network", ip: "192.168.2.10#{i}"
      node.vm.provision "shell", path:  "./join-command.sh"
    end
  end
end